In [124]:
import numpy as np

In [125]:
a = np.array([1,2,3,4])

In [126]:
a

array([1, 2, 3, 4])

In [127]:
list= [1,2,3,4]

In [128]:
list

[1, 2, 3, 4]

In [129]:
#Listeden array yapma
b = np.array(list)

In [130]:
b

array([1, 2, 3, 4])

In [131]:
type(a)

numpy.ndarray

In [132]:
type(list)

list

In [133]:
#tuple dan array yapma
t1 = (4,5,6,7,8)

In [134]:
f = np.array(t1)

In [135]:
type(f)

numpy.ndarray

In [136]:
f

array([4, 5, 6, 7, 8])

In [137]:
for i in f:
    print(i)

4
5
6
7
8


In [138]:
for i in f:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [139]:
#Otomatik olarak değişir değer tiplerini floatnp. veri tipine dönüştürek işlemi gerçekleştiriyor.
a = np.array([1.,2.,3,5.6,6.9])

In [140]:
for i in a :
    print(type(i))

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [141]:
#ZEROS and ONES
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [142]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [143]:
np.zeros(10,dtype="int16")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [144]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [145]:
np.ones(6)*22

array([22., 22., 22., 22., 22., 22.])

In [146]:
np.full(8,5)

array([5, 5, 5, 5, 5, 5, 5, 5])

In [147]:
#Çok boyutlu arrayler

np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [148]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [149]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [151]:
np.arange(0,3,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [152]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [153]:
np.random.rand(5)#0 ile 1 arası üretir

array([0.49752883, 0.89631961, 0.01424148, 0.37192122, 0.24939589])

In [154]:
np.random.randint(0,10)

4

In [155]:
np.random.randint(0,10,(3,4))

array([[9, 4, 0, 8],
       [4, 0, 2, 2],
       [3, 6, 7, 8]])

In [156]:
a = np.random.randint(1,10,size=10)
a

array([1, 9, 1, 5, 9, 4, 1, 7, 5, 8])

In [157]:
a.ndim#boyut sayısı

1

In [158]:
a.shape

(10,)

In [159]:
b = np.random.randint(1,10,(3,4))

In [160]:
b.size

12

In [161]:
b.shape

(3, 4)

In [162]:
a.size

10

In [163]:
a.dtype

dtype('int32')

In [164]:
a = np.arange(1,10).reshape(3,3)

In [165]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [166]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])

In [168]:
np.concatenate([a,b])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [169]:
a1 = ([1,2,3],[4,5,6])
a2 = ([10,20,30],[40,50,60])

In [170]:
np.concatenate((a1,a2),axis=1)

array([[ 1,  2,  3, 10, 20, 30],
       [ 4,  5,  6, 40, 50, 60]])

In [171]:
a1

([1, 2, 3], [4, 5, 6])

In [172]:
a2

([10, 20, 30], [40, 50, 60])

In [173]:
a1 = np.array(([1,2,3],[4,5,6]))
a2 = np.array(([10,20,30]))

In [174]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [175]:
a2

array([10, 20, 30])

In [176]:
#vstack

In [177]:
np.vstack([a1,a2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [10, 20, 30]])

In [178]:
x = np.array(([1,2,3],[4,5,6]))
y = np.array(([7,8],[10,20]))

In [179]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [180]:
y

array([[ 7,  8],
       [10, 20]])

In [181]:
np.hstack([x,y])

array([[ 1,  2,  3,  7,  8],
       [ 4,  5,  6, 10, 20]])

In [182]:
a = np.random.randint(1,10,12)

In [183]:
a

array([8, 1, 4, 1, 2, 6, 6, 9, 1, 6, 3, 3])

In [184]:
np.split(a,[15])

[array([8, 1, 4, 1, 2, 6, 6, 9, 1, 6, 3, 3]), array([], dtype=int32)]

In [185]:
np.split(a,[5,7])

[array([8, 1, 4, 1, 2]), array([6, 6]), array([9, 1, 6, 3, 3])]

In [186]:
np.random.randint(1,20,12)

array([19, 11, 11, 10,  3, 17,  2,  4,  1,  9, 15, 14])

In [187]:
a

array([8, 1, 4, 1, 2, 6, 6, 9, 1, 6, 3, 3])

In [188]:
a[4]

2

In [189]:
b = np.random.randint(12,size=(3,4))

In [190]:
b

array([[ 5,  6,  8,  2],
       [11,  4,  7,  4],
       [ 4,  1,  3,  9]])

In [191]:
b[1,1]

4

In [192]:
b[1][1]

4

In [193]:
b = np.random.randint(20,size=(5,4))

In [194]:
b

array([[ 2,  6,  4, 19],
       [ 4, 17,  1, 13],
       [ 1,  1, 16,  0],
       [ 9,  0, 15, 17],
       [ 1,  6, 11,  4]])

In [195]:
b[2][1:4]

array([ 1, 16,  0])

In [196]:
b[2,1:]

array([ 1, 16,  0])

In [197]:
b = np.random.randint(50, size = (10,5))

In [198]:
b

array([[18, 45, 29,  2, 11],
       [ 0, 11, 24, 37, 25],
       [49, 29, 17, 32, 10],
       [ 4,  9, 48,  4,  2],
       [21,  4,  9, 22, 21],
       [ 3, 12,  9, 39, 13],
       [34, 12, 42, 10, 38],
       [46, 41, 40, 16, 11],
       [44, 47, 45, 24, 28],
       [ 6, 37, 29,  9, 40]])

In [199]:
b[4:6,1:3]

array([[ 4,  9],
       [12,  9]])

In [200]:
b = np.random.randint(0,20,10)

In [201]:
b

array([17,  3,  4,  8, 13, 15,  6,  7,  0,  2])

In [202]:
b[3] = 15

In [203]:
b

array([17,  3,  4, 15, 13, 15,  6,  7,  0,  2])

In [204]:
list1 = [1,2,3,4,5,6]
list2 = list1

In [205]:
list1

[1, 2, 3, 4, 5, 6]

In [206]:
list2

[1, 2, 3, 4, 5, 6]

In [207]:
list1[1]=10

In [208]:
list1

[1, 10, 3, 4, 5, 6]

In [209]:
list2

[1, 10, 3, 4, 5, 6]

In [210]:
list2 = np.copy(list1)

In [211]:
list2

array([ 1, 10,  3,  4,  5,  6])

In [212]:
list1[1]=546

In [213]:
list1

[1, 546, 3, 4, 5, 6]

In [214]:
list2

array([ 1, 10,  3,  4,  5,  6])

In [215]:
a = np.arange(1,8)

In [216]:
a>5

array([False, False, False, False, False,  True,  True])

In [217]:
b = np.random.randint(50,size=(10,5))

In [218]:
np.sum(b>5)

46

In [219]:
#1
np.arange(1,7)

array([1, 2, 3, 4, 5, 6])

In [220]:
#2
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [221]:
#3
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [222]:
#4
np.full([4,5],8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [223]:
#5
np.arange(20,50,3)

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [224]:
#6
np.array([1,2,3,4,5,6,7,8,9,10])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [225]:
#7
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [226]:
#8
np.random.randn(3,4)

array([[-0.82598944, -1.21772611, -0.86276576,  0.58419844],
       [ 0.75532571,  1.3030055 ,  0.45203293, -0.96931079],
       [-0.23645039, -1.42869873, -0.18825066,  0.80514828]])

In [227]:
#9
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [228]:
a=np.random.rand(10)


In [229]:
a

array([0.18378577, 0.26034738, 0.85606767, 0.05126449, 0.87883739,
       0.26459744, 0.28434404, 0.46566333, 0.20429583, 0.60244235])

In [230]:
max(a)

0.8788373868171803

In [231]:
min(a)

0.05126449486429907

In [232]:
a = np.random.randint(1,30,20).reshape(5,4)

In [233]:
a

array([[ 9, 10, 10, 26],
       [22,  7, 22, 14],
       [ 6,  2, 29,  1],
       [ 1,  3,  3, 25],
       [20, 15,  9,  9]])

In [234]:
a[1,:]

array([22,  7, 22, 14])

In [235]:
a[2,3]

1

In [236]:
a[:,3]

array([26, 14,  1, 25,  9])

In [237]:
a=np.arange(1,7).reshape(2,3)

In [238]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]


In [239]:
a=np.random.rand(6)
a*5


array([3.59267713, 2.26424384, 3.62736827, 3.80891412, 1.25575762,
       1.46082226])

In [240]:
sum(a)
2.7341623982675354


2.7341623982675354

In [241]:
np.median(a)
0.6037817371739695


0.6037817371739695

In [242]:
# Standart sapma
np.std(a)
0.24551707547157878


0.24551707547157878